name: SiegeTeleportBlock
version: "1.1"
main: me.ethereal.siegeteleportblock.SiegeTeleportBlock
api-version: 1.16
author: Bit
depend: [ SiegeWar ]

commands:
  stb:
    Permission: stb.admin


permissions:
  stb.admin:
    default: op