name: SiegeTeleportBlock
version: "1.0"
main: me.ethereal.siegeteleportblock.SiegeTeleportBlock
api-version: 1.16
authors: [ Bit ]
depend: [ SiegeWar ]

commands:
  stb:
    Permission: stb.admin


permissions:
  stb.admin:
    default: op